import type { Metadata } from "next";
import { Toaster, toast } from "sonner";
import { Inter } from "next/font/google";
import "./globals.css";
import Navigation from "./components/navigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html data-theme="cmyk" lang="en">
      <body className={inter.className}>
        <Toaster />
        <Navigation />
        {children}
      </body>
    </html>
  );
}
